server.port=0

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:aggregator}
stats.kafka.topic.user-actions=${STATS_KAFKA_TOPIC_USER_ACTIONS:stats.user-actions.v1}
stats.kafka.topic.events-similarity=${STATS_KAFKA_TOPIC_EVENTS_SIMILARITY:stats.events-similarity.v1}

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
