server.port=0
grpc.server.port=0

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/analyzer}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:analyzer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:analyzer}

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:analyzer}
stats.kafka.topic.user-actions=${STATS_KAFKA_TOPIC_USER_ACTIONS:stats.user-actions.v1}
stats.kafka.topic.events-similarity=${STATS_KAFKA_TOPIC_EVENTS_SIMILARITY:stats.events-similarity.v1}

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
