server.port=0

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-events}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:events}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:events}

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

grpc.client.collector.address=${GRPC_CLIENT_COLLECTOR_ADDRESS:discovery:///collector}
grpc.client.analyzer.address=${GRPC_CLIENT_ANALYZER_ADDRESS:discovery:///analyzer}
user.service.id=${USER_SERVICE_ID:user-service}
request.service.id=${REQUEST_SERVICE_ID:request-service}
category.service.id=${CATEGORY_SERVICE_ID:category-service}
