server.port=8080

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=comment-service-admin-user-comments-api
spring.cloud.gateway.routes[0].uri=lb://comment-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/users/*/events/*/comments,/admin/users/*/comments/*

spring.cloud.gateway.routes[1].id=user-service-api
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/users/**

spring.cloud.gateway.routes[2].id=comment-service-event-comments-api
spring.cloud.gateway.routes[2].uri=lb://comment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/events/*/comments

spring.cloud.gateway.routes[3].id=request-service-api
spring.cloud.gateway.routes[3].uri=lb://request-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/users/*/requests,/users/*/requests/**,/users/*/events/*/requests

spring.cloud.gateway.routes[4].id=category-service-api
spring.cloud.gateway.routes[4].uri=lb://category-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/categories,/categories/**,/admin/categories,/admin/categories/**

spring.cloud.gateway.routes[5].id=compilation-service-api
spring.cloud.gateway.routes[5].uri=lb://compilation-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/compilations,/compilations/**,/admin/compilations,/admin/compilations/**

spring.cloud.gateway.routes[6].id=comment-service-api
spring.cloud.gateway.routes[6].uri=lb://comment-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/comments,/comments/**,/admin/comments,/admin/comments/**

spring.cloud.gateway.routes[7].id=event-service-api
spring.cloud.gateway.routes[7].uri=lb://event-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/events,/events/**,/admin/events,/admin/events/**,/users/*/events,/users/*/events/**

spring.cloud.gateway.routes[8].id=stats-server-api
spring.cloud.gateway.routes[8].uri=lb://stats-server
spring.cloud.gateway.routes[8].predicates[0]=Path=/hit,/stats
