server.port=0

spring.sql.init.mode=never

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

user.service.id=${USER_SERVICE_ID:user-service}
event.service.id=${EVENT_SERVICE_ID:event-service}
