server.port=0

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-users}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:users}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:users}

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
