spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service-admin-user-comments-api
          uri: lb://main-service
          predicates:
            - Path=/admin/users/*/events/*/comments,/admin/users/*/comments/*
        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: main-service-api
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**,/comments/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}"
