spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:compilation-service-test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: "${COMPILATION_TEST_DB_PASSWORD:}"
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    enabled: false
